タスク1　初回対応
hi-date-ns/sample-vue-application pull request #2
Opened 2024-12-12 06:07 UTC by hi-date-ns

## 詳細
- 以下に対応しました
  - Main, Form, Tableの作成
  - Optional（dev,form,table）

## 画面キャプチャ 
- 初期表示
![image](https://github.com/user-attachments/assets/2d4cfc1c-ecea-456f-83bf-127a15e75891)

> MainコンポーネントのFormコンポーネント / Tableコンポーネントの表示切り替え機能の実装

- ボタン押下で機能の表示を切り替える
![image](https://github.com/user-attachments/assets/16d81a45-444a-4b10-9eb6-6ea57b9ffb68)
![image](https://github.com/user-attachments/assets/a61e4a00-8686-473e-b1ee-8873456d3e89)

- 再度押下で非表示
![image](https://github.com/user-attachments/assets/ab982311-a1b7-4f89-896b-24033b84e7d7)

2024-12-12 07:48 UTC, takumi-13 requested changes
全体的によくかけていると思います！流石です！！

レイアウトと変数定義に対するコメントと、書けそうなので課題に記載した内容から追加で書いてほしい点のコメントを記載しています。

ご対応お願いします！

2024-12-12 07:48 UTC, takumi-13 commented on src/App.vue
> +    <!-- <div class="text-5xl text-bold bg-red-500">Hello,World</div> -->
ここは削除してOKです！
不要なコードを残しておいても後で見返したときのノイズにしかならないので、いらない箇所はガンガン削除していきましょう！
見返したいときに残しておきたいという意図であれば、GitのHistoryでいつでも見返せますし

2024-12-12 07:48 UTC, takumi-13 commented on src/App.vue
> +      <!-- <Test1 msg="Test1" :count="countTest1" :set-count="setCountTest1" />
同上

2024-12-12 07:48 UTC, takumi-13 commented on src/components/TableComponent.vue
> +          </td>
ここの各要素もv-for使って繰り返し表示するようにしましょうか！
`<td class="px-1 py-1 table-auto border-collapse border border-gray-900 hover:bg-gray-100 text-right">`と何回も書いていて冗長なので！

2024-12-12 07:48 UTC, takumi-13 commented on src/components/TableComponent.vue
> +          <th class="px-1 py-1 able-auto border-collapse border border-gray-900 bg-red-200">支出９</th>
thもv-for使えるといいですね！

2024-12-12 07:48 UTC, takumi-13 commented on src/components/HouseholdMain.vue
> +  </div>
FormとTableは排他的制御で表示するようにしたいです。

今のままだと、「フォーム」ボタンと「テーブル」ボタンを押下した状態（selectFormFlag = True, selectFormFlag = Trueの状態）の画面表示としてFormComponentとTableComponentが同時に表示されますよね？
どちらかだけが一方のみが必ず表示されるようにしてください！

2024-12-12 07:48 UTC, takumi-13 commented on src/components/HouseholdMain.vue
> +  </div>
コード上でもそのように制御できるように変数設計してあげるといいかもです。
１．フォーム表示フラグを見てあげてどちらを表示するか決めるような変数定義
２．１で定義した変数を参照して表示内容を決める　など

2024-12-12 07:48 UTC, takumi-13 commented on src/components/TableComponent.vue
> +          <th class="px-1 py-1 able-auto border-collapse border border-gray-900 bg-red-200">支出９</th>
加えて、「日付」・「支出1」など表示する内容を定数として定義してあげてそちらを参照するように変更してみましょう！

2024-12-12 07:48 UTC, takumi-13 commented on src/components/TableComponent.vue
> +        },
テストデータなのでこのままでもよいのですが、配列関数の練習をして頭の体操しましょうか！
この内容をワンライナーで定義してみてください。
イメージとしては下記のような形です。
const TABLE_DATES = [X,Y,Z].map((item,index) => 要素を表現)

2024-12-12 07:48 UTC, takumi-13 commented on src/components/HouseholdMain.vue
> +      // 表示フラグ切り替え
好みの問題だとは思いますけど、あまり変数名としてFlagという言葉は使いたくないです。
・理由：Flag自体が意味を持たない

あと`select`は動詞なので形容詞の`selected`にした方がいいかなと思います。
動詞から始まると関数に見えるので。

好みやコーディングルールによるので一般的には言えないですが、boolean型の変数名はis/has/canなど + 形容詞＋対象が多いのかなと思うので、
`selectFormFlag` ⇒ `isSelectedForm`
`selectTableFlag` ⇒ `isSelecedTable
とかが適当ですかね？

2024-12-12 07:48 UTC, takumi-13 commented on src/components/HouseholdMain.vue
> +  </div>
フォームとテーブルはサイドバーとして表示するようにしてあげたいです。
イメージとしては添付画像のような形です
![image](https://github.com/user-attachments/assets/cb69e925-1db9-4813-aba3-06fc1a1f4d11)

2024-12-12 08:18 UTC, takumi-13 commented on src/components/HouseholdMain.vue
> +  </div>
` v-if="selectTableFlag == true"`
原則厳密等価演算子`===`を使うようにお願いします！
https://zenn.dev/bokutano26/articles/442f11f4ec69bf

2024-12-16 06:53 UTC, hi-date-ns commented
レビューいただきありがとうございました。
指摘について対応しましたのでご確認お願いします。

-  スクショ

![image](https://github.com/user-attachments/assets/197e459a-1e84-461a-ba86-945e7ee3566c)
![image](https://github.com/user-attachments/assets/4a07465b-4e9f-493f-beea-0065335480e0)
![image](https://github.com/user-attachments/assets/4a3538a3-3197-4c6a-a28e-0a44c41391ab)

2024-12-17 04:50 UTC, takumi-13 requested changes

2024-12-17 04:50 UTC, takumi-13 commented on src/components/HouseholdMain.vue
> +      const selectedFunction = ref('');
この変更でいいと思う！
ただ、`selectedFunction`の型を定義してあげたい！
現時点では`selectedFunction`はformとtableの二種類しかないため、どこかで誤って`tble`みたいなものが入ったら検知してあげられるといい
ではそれをどうやるか？なんだけど、こんな感じだといいかなーと
型については調べると面白いから調べてみるといいかも！
```
const FUNCTION_TABLE = 'table'
const FUNCTION_FORM = 'form'
type Function = FUNCTION_TABLE | FUNCTION_FORM 
const selecedFunction: Function = ref(FUNCTION_TABLE)
```

2024-12-17 04:50 UTC, takumi-13 commented on src/components/HouseholdMain.vue
> +    <button class="block text-bold hover:bg-rose-200 active:scale-95 p-5 max-h-20" @click="selectedFunction = 'form'">
formがマジックナンバーになってるので、固定値を用意してあげた方がよさそう

2024-12-17 04:50 UTC, takumi-13 commented on src/components/HouseholdMain.vue
> +    <button class="block text-bold hover:bg-rose-200 active:scale-95 p-5" @click="selectedFunction = 'table'">
同上

2024-12-17 04:50 UTC, takumi-13 commented on src/components/HouseholdMain.vue
> +    <div class="flex-1 p-5 rounded-lg" v-if="selectedFunction === 'form'">
同上

2024-12-17 04:50 UTC, takumi-13 commented on src/components/HouseholdMain.vue
> +    <div class="flex-1 p-5 rounded-lg" v-if="selectedFunction === 'table'">
同上

2024-12-17 04:50 UTC, takumi-13 commented on src/components/TableComponent.vue
> +      }));
いいですねーーー素敵！！

2024-12-17 04:50 UTC, takumi-13 commented on src/components/TableComponent.vue
> +        </tr>
とてもいいと思います！

2024-12-17 05:48 UTC, takumi-13 commented on src/components/HouseholdMain.vue
> +      const selectedFunction = ref('');
もっといい書き方もあったりするので、気になったら調べて書いてみるとベターです。
※必須ではないです
```
const FUNCTION_TYPE = // 配列でtable,formを定義（定義する際にとあるおまじないが必要）
type Function = // FUNCTION_TYPEかあとある方法を使用して配列から型を定義する
```

2024-12-17 05:48 UTC, takumi-13 commented on src/components/TableComponent.vue
> +      }));
※感想です

2024-12-17 05:49 UTC, takumi-13 commented on src/components/TableComponent.vue
> +        </tr>
※感想です

2024-12-17 08:39 UTC, takumi-13 approved these changes
lgtm

2024-12-17 08:39 UTC, merged