タスク2　初回対応
hi-date-ns/sample-vue-application pull request #4
Opened 2024-12-20 02:26 UTC by hi-date-ns

## 詳細
- 以下に対応しました
  - テーブルの本実装
  - フォームの充実
  - 各Optional
  
## 画面キャプチャ
- 初期表示
![image](https://github.com/user-attachments/assets/f89c6bba-056b-4a83-ad71-639d048c3261)
> Optional（難易度：★★★☆☆）：曜日によって行の色を変更してみよう！
![image](https://github.com/user-attachments/assets/3d3becde-3db7-4010-abad-8d6a5dff0ae4)

- 画面操作
> ・日だけ1~30を選択できるようなプルダウンとして定義してみてほしい
> さらに年月日を選択する横に[ 食費 ▽]みたいなプルダウンを追加して、食費と固定費を選択できるようにしよう。

![image](https://github.com/user-attachments/assets/5da08dc6-d68b-42b1-a2b8-9fff700ed751)
![image](https://github.com/user-attachments/assets/44aaadea-7129-407d-814d-065f545ff8e4)

> ”追加ボタン”をフォームの横に追加し、追加ボタン押下時に値がテーブルの選択した日付の食費/固定費に反映されるようにしてみよう

<img width="443" alt="image" src="https://github.com/user-attachments/assets/edc8a9a6-a9a6-48fc-a096-7c13aa12c474" />
<img width="542" alt="image" src="https://github.com/user-attachments/assets/db94fea5-0e0e-4d04-97b8-ad13cba48c69" />

> Optional（難易度：★★☆☆☆）：Tableの日付を押下時にFormに切り替わり、

![image](https://github.com/user-attachments/assets/bc87d440-e54c-42e1-a303-6b6cad599843)

2024-12-23 09:47 UTC, takumi-13 requested changes
全体的にmapの使い方の見直しとpushを使わない書き方を考えてみましょう！
TypeScriptのベストプラクティスとして「関数型プログラミング」といった考え方があります。
これを実践できるようになると簡潔に奇麗でわかりやすく、不具合が起こりにくいコードを書くことができるようになるのでぜひここで学んでほしいです！

いくつかエッセンスはあるのですが、第一歩としてイメージしてほしいのは、
1. 配列を宣言する
2. その配列をベースに変更を加える
を繰り返し行っていくことです。

2024-12-23 09:47 UTC, takumi-13 commented on src/components/FormComponent.vue
> +  /* eslint-disable no-console*/
eslintを無視する記載は開発中は外してもいいですが、
Pushする際は原則削除するようにお願いします。
eslintはチームとしての開発ルールを記載したものなので！

2024-12-23 09:47 UTC, takumi-13 commented on src/components/FormComponent.vue
> +    // eslint-disable-next-line complexity
ここ、eslintを無視せずに記載する方法を考えてみましょうか！

2024-12-23 09:47 UTC, takumi-13 commented on src/components/FormComponent.vue
> +        props.selectedMonth !== undefined ? props.selectedMonth : calendar.value[0].month
``
      const selectedYear = ref<number | null>(
        props.selectedYear !== undefined ? props.selectedYear : calendar.value[0].year
      );
``
`??`を使うと簡潔に書けますので、使ってみましょう！

2024-12-23 09:47 UTC, takumi-13 commented on src/components/FormComponent.vue
> +  function updateCostTableDate(
関数定義はアロー関数で統一しましょうか！

2024-12-23 09:47 UTC, takumi-13 commented on src/components/FormComponent.vue
> +      if (selectedYear === undefined || selectedMonth === undefined || selectedDate === undefined) return;
早期リターン使うのはとてもいいと思います！

`selectedYear === undefined || selectedMonth === undefined || selectedDate === undefined`

1. ここは変数定義してあげたいですね。
2. undefinedとの比較を行いたいのであれば、この場合`null`を弾きたい理由が特にないのであれば、`!!`を使ってあげると簡潔になります
こんなかんじですかねー
`const isvalid = !!selectedYear || !!selectedMonth | !!selectedDate`

2024-12-23 09:47 UTC, takumi-13 commented on src/components/FormComponent.vue
> +    // eslint-disable-next-line complexity
おそらく処理が複雑になってしまっていてeslintでエラーが出力されているので、適切に関数を分解してみましょう

2024-12-23 09:47 UTC, takumi-13 commented on src/components/FormComponent.vue
> +    costTableDate.map((item) => {
この書き方はcostTableDateを更新してしまうためあまり良い書き方ではないです。
`map`は配列を基に新しい配列を作成する関数なので、この関数自体を下記のような形で書き換えてみてください。
```
const x = [x,y,z].map()
return x
```
また、find.filter,some,など配列に対してほしい値と一致するか検索する関数もあるため、適切に使い分けてみるとコードがきれいになるかと思います！

2024-12-23 09:47 UTC, takumi-13 commented on src/components/FormComponent.vue
> +        item.date === selectedDate &&
意味のまとまりごとに変数で固めてあげるとわかりやすいコードになると思いますので、意識してみるといいかもです！

2024-12-23 09:47 UTC, takumi-13 commented on src/components/HouseholdMain.vue
> +  export function createCostTableDate(
アロー関数で統一しましょう

2024-12-23 09:47 UTC, takumi-13 commented on src/components/TableComponent.vue
> +      if (calendarArray.day === DAYS_NUMBER.SUNDAY) {
if文使わないで書こうとするとどうなります？
ヒントはfind/filterです。

2024-12-23 09:47 UTC, takumi-13 commented on src/components/TableComponent.vue
> +      if (calendarArray.day === DAYS_NUMBER.SUNDAY) {
` calendarArray.map((calendarArray) => {`
この書き方をするのであれば、`forEach`を使うべきですね。
mapは与えられた配列から新しい配列を作成してしまうので。

また、dayColorArrayを最初に宣言してそこに値を詰めていっていますが、下記のような形でワンライナーで書いてみましょうか。
```
const colorDefinition = [
{
  definition: DAYS_NUMBER.SUNDAY
  color :TEXT_COLOR.TEXT_RED_500
}
ほかの曜日も同様
]
const dayColorArray = calenderArray.map((elm) =>colorDefinitionと一致するか判定する )
```

2024-12-23 09:47 UTC, takumi-13 commented on src/components/TableComponent.vue
> +              setSelectedFunction(FUNCTION_FORM), setSelectedCalendar(costDate.year, costDate.month, costDate.date)
これらの処理を関数化してあげておきたいですね。

2024-12-23 09:47 UTC, takumi-13 commented on src/utils/commonUtils.ts
> +  }
pushとfor文を使わないで表現してみましょうか

2024-12-25 08:57 UTC, hi-date-ns commented
レビューいただきありがとうございました。
指摘箇所について対応しましたので、ご確認をお願いいたします。

2024-12-26 03:29 UTC, takumi-13 requested changes

2024-12-26 03:29 UTC, takumi-13 commented on src/components/TableComponent.vue
> +  };
特に`dayColorArray`に束縛する必要がないので、
```
  const createDayColorArray = (calendarArray: Calendar[]): string[] => {
    return calendarArray.map((calendar) =>
      String(
        // calendarArray分比較して対応する色を配列化
        DAYS_COLOR_DEFINITION.find((dayColor) => calendar.day === dayColor.definition)?.color ??
          TEXT_COLOR.TEXT_BLACK_500
      )
    );
  };
```
でよいです。
そして、
```
const func () => {
 return XXXX
}
```
は{}の中がreturnのみなので、
```
const func () => XXX 
```
と書けます。
そのため、このコードは
```
  const createDayColorArray = (calendarArray: Calendar[]): string[] => calendarArray.map((calendar) =>
      String(
        // calendarArray分比較して対応する色を配列化
        DAYS_COLOR_DEFINITION.find((dayColor) => calendar.day === dayColor.definition)?.color ??
          TEXT_COLOR.TEXT_BLACK_500
      )
    );
```
と短縮可能です。

2024-12-26 03:29 UTC, takumi-13 commented on src/components/HouseholdMain.vue
> +  };
短縮可能（詳細はほかの箇所で記載）

2024-12-26 03:29 UTC, takumi-13 commented on src/components/FormComponent.vue
> +    if (updateCostTableDate === undefined) return;
undefinedとの比較ではなく書けそうですね！

2024-12-26 03:29 UTC, takumi-13 commented on src/components/FormComponent.vue
> +    }
if文使わないで書く場合はどんな形にできそうですかね？
ヒント：更新対象と選択対象をMappingするようなオブジェクトの配列を用意して配列関数を用いて変更できそう！

2024-12-26 03:29 UTC, takumi-13 commented on src/utils/commonUtils.ts
> +export function createCalendar(): Calendar[] {
アロー関数に統一しておきましょう！

2024-12-27 01:24 UTC, merged